services:
  - type: web
    name: strapi-backend
    env: node
    plan: free
    buildCommand: echo "Skipping build step"
    startCommand: npm run develop
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_CLIENT
        value: sqlite
